-- AI Product Search & Intelligence Engine
-- Run this file in your MySQL server to create the DB, table, and seed data.
-- Example: mysql -u root -p < schema.sql

CREATE DATABASE IF NOT EXISTS product_search_db;
USE product_search_db;

CREATE TABLE IF NOT EXISTS products (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    product_id   VARCHAR(20)     NOT NULL UNIQUE,
    name         VARCHAR(255)    NOT NULL,
    description  TEXT            NOT NULL,
    price        DECIMAL(10, 2)  NOT NULL,
    category     VARCHAR(100),
    brand        VARCHAR(100),
    color        VARCHAR(50)
);

-- IGNORE makes this seed script safe to run again without duplicating products.
INSERT IGNORE INTO products (product_id, name, description, price, category, brand, color) VALUES
('P101', 'Black Leather Formal Shoes', 'Comfortable black leather formal shoes suitable for office', 2499.00, 'Shoes', 'Generic', 'Black'),
('P102', 'Black Running Shoes', 'Lightweight black running shoes', 2199.00, 'Shoes', 'Generic', 'Black'),
('P103', 'Brown Formal Shoes', 'Comfortable brown formal shoes suitable for office', 2799.00, 'Shoes', 'Generic', 'Brown'),
('P104', 'Black Casual Shoes', 'Comfortable black casual shoes', 1999.00, 'Shoes', 'Generic', 'Black'),
('P105', 'Black Comfort Formal Shoes', 'Comfortable black formal shoes with cushioned sole for all day office wear', 2799.00, 'Shoes', 'Generic', 'Black'),
('P106', 'Black Office Formal Shoes', 'Black formal shoes designed for daily office use', 2399.00, 'Shoes', 'Generic', 'Black'),
('P107', 'White Sneakers', 'Lightweight white casual sneakers for everyday wear', 1799.00, 'Shoes', 'Generic', 'White'),
('P108', 'Lightweight Waterproof Running Jacket', 'Waterproof lightweight jacket ideal for running and outdoor use', 3299.00, 'Jacket', 'Generic', 'Blue'),
('P109', 'Navy Party Shirt', 'Slim fit navy shirt suitable for party and evening wear', 1499.00, 'Shirt', 'Generic', 'Navy'),
('P110', 'Brown Casual Sandals', 'Comfortable brown sandals for casual outdoor use', 999.00, 'Sandals', 'Generic', 'Brown'),
('P111', 'White Canvas Sneakers', 'Comfortable white canvas sneakers for casual everyday wear', 1899.00, 'Shoes', 'Stride', 'White'),
('P112', 'Navy Mesh Running Shoes', 'Breathable navy mesh running shoes with lightweight cushioning', 2699.00, 'Shoes', 'Stride', 'Navy'),
('P113', 'Brown Leather Loafers', 'Classic brown leather loafers for office and formal occasions', 2999.00, 'Shoes', 'Heritage', 'Brown'),
('P114', 'Grey Sports Sneakers', 'Grey sports sneakers with flexible sole for gym workouts', 2299.00, 'Shoes', 'Active', 'Grey'),
('P115', 'Red Training Shoes', 'Red lightweight training shoes for gym and fitness sessions', 2399.00, 'Shoes', 'Active', 'Red'),
('P116', 'Black Waterproof Hiking Boots', 'Durable black waterproof boots for outdoor travel and hiking', 3899.00, 'Shoes', 'TrailPro', 'Black'),
('P117', 'Beige Casual Loafers', 'Soft beige casual loafers for comfortable daily use', 2099.00, 'Shoes', 'Stride', 'Beige'),
('P118', 'Blue Running Sneakers', 'Blue cushioned running sneakers for long-distance training', 2799.00, 'Shoes', 'Active', 'Blue'),
('P119', 'Green Outdoor Sandals', 'Green waterproof sandals suitable for travel and outdoor walks', 1399.00, 'Sandals', 'TrailPro', 'Green'),
('P120', 'Black Leather Sandals', 'Black leather sandals with padded footbed for casual use', 1599.00, 'Sandals', 'Heritage', 'Black'),
('P121', 'Brown Trekking Sandals', 'Brown trekking sandals with secure straps for outdoor adventures', 1799.00, 'Sandals', 'TrailPro', 'Brown'),
('P122', 'White Sports Sandals', 'White lightweight sports sandals for beach and casual wear', 1299.00, 'Sandals', 'Active', 'White'),
('P123', 'Navy Slim Fit Shirt', 'Navy slim fit cotton shirt for office and party wear', 1699.00, 'Shirt', 'UrbanFit', 'Navy'),
('P124', 'White Formal Cotton Shirt', 'Crisp white formal cotton shirt for daily office wear', 1499.00, 'Shirt', 'UrbanFit', 'White'),
('P125', 'Black Casual Linen Shirt', 'Breathable black linen shirt for casual evenings and travel', 1599.00, 'Shirt', 'Coastline', 'Black'),
('P126', 'Blue Checked Casual Shirt', 'Blue checked casual shirt with a relaxed fit', 1399.00, 'Shirt', 'Coastline', 'Blue'),
('P127', 'Pink Party Shirt', 'Pink slim fit party shirt for celebrations and evening events', 1799.00, 'Shirt', 'UrbanFit', 'Pink'),
('P128', 'Grey Oxford Formal Shirt', 'Grey oxford formal shirt suitable for professional office use', 1899.00, 'Shirt', 'Heritage', 'Grey'),
('P129', 'Red Printed T-Shirt', 'Red printed cotton t-shirt for casual daily wear', 799.00, 'T-Shirt', 'Active', 'Red'),
('P130', 'Black Performance T-Shirt', 'Black moisture-wicking t-shirt for gym and running', 999.00, 'T-Shirt', 'Active', 'Black'),
('P131', 'White Oversized T-Shirt', 'White oversized cotton t-shirt for relaxed casual style', 899.00, 'T-Shirt', 'Coastline', 'White'),
('P132', 'Navy Polo T-Shirt', 'Navy polo t-shirt for smart casual office and weekend wear', 1199.00, 'T-Shirt', 'UrbanFit', 'Navy'),
('P133', 'Blue Denim Jacket', 'Blue denim jacket for casual travel and everyday layering', 2499.00, 'Jacket', 'Coastline', 'Blue'),
('P134', 'Black Bomber Jacket', 'Black lightweight bomber jacket for casual evening wear', 2999.00, 'Jacket', 'UrbanFit', 'Black'),
('P135', 'Green Waterproof Jacket', 'Green waterproof jacket for outdoor travel during rain', 3599.00, 'Jacket', 'TrailPro', 'Green'),
('P136', 'Brown Leather Jacket', 'Brown leather jacket for party and premium casual style', 4999.00, 'Jacket', 'Heritage', 'Brown'),
('P137', 'Grey Running Jacket', 'Grey lightweight running jacket with reflective details', 2799.00, 'Jacket', 'Active', 'Grey'),
('P138', 'Beige Cotton Jacket', 'Beige cotton jacket for comfortable casual office wear', 2699.00, 'Jacket', 'Coastline', 'Beige'),
('P139', 'Black Slim Fit Jeans', 'Black slim fit jeans for casual office and party outfits', 1999.00, 'Jeans', 'UrbanFit', 'Black'),
('P140', 'Blue Regular Fit Jeans', 'Classic blue regular fit jeans for everyday casual wear', 1899.00, 'Jeans', 'Coastline', 'Blue'),
('P141', 'Grey Stretch Jeans', 'Grey stretch jeans with flexible comfort for travel', 2099.00, 'Jeans', 'UrbanFit', 'Grey'),
('P142', 'Navy Denim Jeans', 'Navy denim jeans for relaxed casual weekend use', 1799.00, 'Jeans', 'Coastline', 'Navy'),
('P143', 'Black Digital Watch', 'Black digital sports watch with alarm and water resistance', 1599.00, 'Watch', 'Active', 'Black'),
('P144', 'Brown Leather Watch', 'Brown leather strap analog watch for formal office use', 2499.00, 'Watch', 'Heritage', 'Brown'),
('P145', 'Silver Casual Watch', 'Silver dial casual watch for daily and party wear', 2199.00, 'Watch', 'UrbanFit', 'Grey'),
('P146', 'Blue Fitness Watch', 'Blue fitness watch with activity tracking for gym sessions', 2999.00, 'Watch', 'Active', 'Blue'),
('P147', 'Black Travel Backpack', 'Black spacious backpack for office commute and travel', 1899.00, 'Bag', 'TrailPro', 'Black'),
('P148', 'Brown Leather Messenger Bag', 'Brown leather messenger bag for professional office use', 3299.00, 'Bag', 'Heritage', 'Brown'),
('P149', 'Navy Gym Bag', 'Navy durable gym bag with shoe compartment', 1499.00, 'Bag', 'Active', 'Navy'),
('P150', 'Pink Casual Tote Bag', 'Pink lightweight tote bag for casual shopping and travel', 1299.00, 'Bag', 'Coastline', 'Pink'),
('P151', 'White Running Cap', 'White breathable running cap for outdoor fitness', 699.00, 'Accessories', 'Active', 'White'),
('P152', 'Black Sports Cap', 'Black adjustable sports cap for gym and casual wear', 649.00, 'Accessories', 'Active', 'Black'),
('P153', 'Brown Leather Belt', 'Brown genuine leather belt for formal office trousers', 999.00, 'Accessories', 'Heritage', 'Brown'),
('P154', 'Black Formal Belt', 'Black formal belt with polished buckle for office wear', 899.00, 'Accessories', 'UrbanFit', 'Black'),
('P155', 'Navy Cotton Kurta', 'Navy cotton kurta for ethnic casual and festival wear', 1599.00, 'Kurta', 'UrbanFit', 'Navy'),
('P156', 'White Embroidered Kurta', 'White embroidered kurta for wedding and festive occasions', 2299.00, 'Kurta', 'Heritage', 'White'),
('P157', 'Blue Casual Kurta', 'Blue lightweight kurta for comfortable daily ethnic wear', 1399.00, 'Kurta', 'Coastline', 'Blue'),
('P158', 'Black Party Sneakers', 'Black stylish sneakers for party and casual evening wear', 2599.00, 'Shoes', 'UrbanFit', 'Black'),
('P159', 'Yellow Lightweight Running Shoes', 'Yellow lightweight running shoes for energetic outdoor workouts', 2499.00, 'Shoes', 'Active', 'Yellow'),
('P160', 'Grey Office Backpack', 'Grey laptop backpack with padded compartment for office commute', 2199.00, 'Bag', 'UrbanFit', 'Grey');
